services:
  bot:
    container_name: cmx_bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      ACCOUNT_TYPE: ${ACCOUNT_TYPE}
      API_KEY_SECRET: ${API_KEY_SECRET}
      API_KEY: ${API_KEY}
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
    volumes:
      - ./src/config/bot_config.json:/src/config/bot_config.json
      - ./logs.log:/logs/log
      - ./src/data/trade_journal.json:/src/data/trade_journal.json
    
  web:
    container_name: web-interface
    build: 
      context: ./web
      dockerfile: Dockerfile
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}