services:
  bot:
    container_name: cmx_bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      ACCOUNT_TYPE: ${ACCOUNT_TYPE}
      API_KEY_SECRET: ${API_KEY_SECRET}
      API_KEY: ${API_KEY}
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
    volumes:
      - ./logs.log:/app/logs.log
      - ./src/data/trade_journal.json:/app/src/data/trade_journal.json
      - ./bot_config.json:/app/bot_config.json
    
  web:
    container_name: web-interface
    ports:
      - "10605:10605"
    build: 
      context: .
      dockerfile: ./web/Dockerfile
    environment:
      ACCOUNT_TYPE: ${ACCOUNT_TYPE}
      API_KEY_SECRET: ${API_KEY_SECRET}
      API_KEY: ${API_KEY}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    volumes:
      - ./bot_config.json:/app/bot_config.json
      - ./metadata.json:/app/metadata.json
    depends_on:
      - bot